### ISSUE TITLE
Required Version

### ISSUE THREAD

**Issue by Tiiiger** [chenpf1025/noisy_label_understanding_utilizing#1]
First I would like to thank you for making your work easy to replicate. I believe this is a truly inspiring paper. 

I am simply writing to ask what is the version of tensorflow and keras that you run these experiments with?

**Comment by chenpf1025** [comment]
Thank you for your interest. The version is as follows:
Python 3.6.4
Keras 2.1.6
Tensorflow 1.7.0

**Comment by chenpf1025** [comment]
> First I would like to thank you for making your work easy to replicate. I believe this is a truly inspiring paper.
> 
> I am simply writing to ask what is the version of tensorflow and keras that you run these experiments with?
